import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider"
import CommonLayout from "./pagesComponents/CommonLayout";
import { Provider as ReduxProvider } from 'react-redux';
import store from '../store';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body suppressHydrationWarning>
        {/* <ReduxProvider store={store}> */}
          <Provider>
            <CommonLayout>
              {children}
            </CommonLayout>
          </Provider>
        {/* </ReduxProvider> */}
      </body>
    </html>
  );
}
